# Generated by Django 4.2.21 on 2025-06-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0002_product_stock_quantity_payment_cartitem_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_number',
        ),
    ]
